language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
  - yarn install
  - yarn snyk:protect
  - yarn snyk:test
script:
  - yarn coverage
  - yarn build
  - yarn coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
after_deploy:
  - yarn snyk:monitor
