language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
  - npm install -g snyk
  - yarn install
  - snyk auth $SNYK_TOKEN
  - snyk test
script:
  - yarn coverage
  - yarn build
  - yarn coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
